# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "164ebe1ed47ce58245711be9eaaa1376"
name = "promotional-banner"
handle = "promotional-banner-10"
application_url = "https://george-accurate-votes-vacancies.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://george-accurate-votes-vacancies.trycloudflare.com/auth/callback",
  "https://george-accurate-votes-vacancies.trycloudflare.com/auth/shopify/callback",
  "https://george-accurate-votes-vacancies.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
